name: Build and deploy

# When to run build and deployment: on any push to main, pull request targetting main,
# or manually telling GitHub to run the workflow.
# We don't want to deploy on a PR; we handle that later.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# The build environment: which version of Node to use and where the output is
env:
  build-path: "KoLmafia" # Given in webpack.config.js in modules.exports.output.path
  node-version: "22"

# What the various parts of building and deploying look like
jobs:
  # Test that the script builds
  testBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.node-version }}

      - name: Build
        run: yarn run build

  # Lint the script (check for common errors and code smells)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.node-version }}

      - name: Linting
        run: yarn run lint

  # Deploy the compiled code to the release branch
  deploy:
    runs-on: ubuntu-latest
    needs: [testBuild, lint] # Only deploy if we pass these checks
    if: github.ref == 'refs/heads/main' # Only deploy the main branch
    permissions:
      contents: "write" # We need to write to the repository to deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.node-version }}

      - name: Build
        run: yarn run build

      - name: Push to Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self # We deploy to our own repo
          BRANCH: release # The branch to deploy to
          FOLDER: ${{ env.build-path }} # The folder to push to the new branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically given to workflows to let them do stuff to the repo
          MESSAGE: "Build: ({sha}) {msg}" # The commit message for the release branch commit
          SKIP_EMPTY_COMMITS: true
